[package]
name = "reduced_row_echelon_form"
version = "0.1.0"
edition = "2021"
description = "`reduced_row_echelon_form` is an api that lets you constuct a Matrix and convert it to RREF"
license = "MIT"
repository = "https://github.com/JEck05/ReducedEchelonForm"

[dependencies]
